env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
globals:
  process: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  react/jsx-uses-vars: 1
  react/jsx-uses-react: 1
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
